name: Trident
main: Trident\Main
version: 1.0.0
api:
  - 3.0.0
  - 4.0.0
load: STARTUP
author: TheNote
authors:
  #Special Tanks vor The Code!
  - CortexPE
description: Aktivate the Trident on pmmp or Altay.
